version: 1
accounts:
  - name: alice
    coins: ["100000000scred", "500000000cred"]
  - name: bob
    coins: ["20000scred","100000000cred"]
validators:
  - name: alice
    bonded: "100000000cred"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000cred"]
genesis:
  app_state:
    staking:
      params:
        bond_denom: "cred"
