// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: credimint/user_credibility.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UserCredibility struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	MinCollateralPercent uint64   `protobuf:"varint,3,opt,name=minCollateralPercent,proto3" json:"minCollateralPercent,omitempty"`
	CreditScore          uint64   `protobuf:"varint,4,opt,name=creditScore,proto3" json:"creditScore,omitempty"`
	RiskLevel            uint64   `protobuf:"varint,5,opt,name=riskLevel,proto3" json:"riskLevel,omitempty"`
	TotalLent            string   `protobuf:"bytes,6,opt,name=totalLent,proto3" json:"totalLent,omitempty"`
	TotalBorrowed        string   `protobuf:"bytes,7,opt,name=totalBorrowed,proto3" json:"totalBorrowed,omitempty"`
	TimesLent            uint64   `protobuf:"varint,8,opt,name=timesLent,proto3" json:"timesLent,omitempty"`
	TimesBorrowed        uint64   `protobuf:"varint,9,opt,name=timesBorrowed,proto3" json:"timesBorrowed,omitempty"`
	LoansList            []uint64 `protobuf:"varint,10,rep,packed,name=loansList,proto3" json:"loansList,omitempty"`
}

func (m *UserCredibility) Reset()         { *m = UserCredibility{} }
func (m *UserCredibility) String() string { return proto.CompactTextString(m) }
func (*UserCredibility) ProtoMessage()    {}
func (*UserCredibility) Descriptor() ([]byte, []int) {
	return fileDescriptor_c084d219758e3bb9, []int{0}
}
func (m *UserCredibility) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserCredibility) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserCredibility.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserCredibility) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCredibility.Merge(m, src)
}
func (m *UserCredibility) XXX_Size() int {
	return m.Size()
}
func (m *UserCredibility) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCredibility.DiscardUnknown(m)
}

var xxx_messageInfo_UserCredibility proto.InternalMessageInfo

func (m *UserCredibility) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserCredibility) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserCredibility) GetMinCollateralPercent() uint64 {
	if m != nil {
		return m.MinCollateralPercent
	}
	return 0
}

func (m *UserCredibility) GetCreditScore() uint64 {
	if m != nil {
		return m.CreditScore
	}
	return 0
}

func (m *UserCredibility) GetRiskLevel() uint64 {
	if m != nil {
		return m.RiskLevel
	}
	return 0
}

func (m *UserCredibility) GetTotalLent() string {
	if m != nil {
		return m.TotalLent
	}
	return ""
}

func (m *UserCredibility) GetTotalBorrowed() string {
	if m != nil {
		return m.TotalBorrowed
	}
	return ""
}

func (m *UserCredibility) GetTimesLent() uint64 {
	if m != nil {
		return m.TimesLent
	}
	return 0
}

func (m *UserCredibility) GetTimesBorrowed() uint64 {
	if m != nil {
		return m.TimesBorrowed
	}
	return 0
}

func (m *UserCredibility) GetLoansList() []uint64 {
	if m != nil {
		return m.LoansList
	}
	return nil
}

func init() {
	proto.RegisterType((*UserCredibility)(nil), "credimint.credimint.UserCredibility")
}

func init() { proto.RegisterFile("credimint/user_credibility.proto", fileDescriptor_c084d219758e3bb9) }

var fileDescriptor_c084d219758e3bb9 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0x33, 0x69, 0xbf, 0xf6, 0xcb, 0x88, 0x0a, 0xa3, 0x8b, 0x01, 0x65, 0x08, 0xe2, 0xa2,
	0xab, 0x16, 0x14, 0x5f, 0xa0, 0xdd, 0x66, 0x21, 0x15, 0x37, 0x6e, 0x24, 0xcd, 0xdc, 0xc5, 0xe0,
	0x24, 0x53, 0xee, 0x8c, 0x7f, 0xfa, 0x16, 0x3e, 0x96, 0xcb, 0x6e, 0x04, 0x97, 0x92, 0xbc, 0x88,
	0xe4, 0x8a, 0x89, 0x05, 0x77, 0xf7, 0xfc, 0xee, 0x99, 0x73, 0x06, 0x2e, 0x4f, 0x0b, 0x04, 0x6d,
	0x4a, 0x53, 0x85, 0xd9, 0xa3, 0x07, 0xbc, 0x27, 0xb9, 0x32, 0xd6, 0x84, 0xcd, 0x74, 0x8d, 0x2e,
	0x38, 0x71, 0xd4, 0x39, 0xa6, 0xdd, 0x74, 0xf6, 0x1e, 0xf3, 0xc3, 0x5b, 0x0f, 0xb8, 0xe8, 0xed,
	0xe2, 0x80, 0xc7, 0x46, 0x4b, 0x96, 0xb2, 0xc9, 0x70, 0x19, 0x1b, 0x2d, 0x24, 0x1f, 0xe7, 0x5a,
	0x23, 0x78, 0x2f, 0xe3, 0x94, 0x4d, 0x92, 0xe5, 0x8f, 0x14, 0x17, 0xfc, 0xb8, 0x34, 0xd5, 0xc2,
	0x59, 0x9b, 0x07, 0xc0, 0xdc, 0x5e, 0x03, 0x16, 0x50, 0x05, 0x39, 0xa0, 0xb7, 0x7f, 0xee, 0x44,
	0xca, 0xf7, 0xa8, 0x3e, 0xdc, 0x14, 0x0e, 0x41, 0x0e, 0xc9, 0xfa, 0x1b, 0x89, 0x53, 0x9e, 0xa0,
	0xf1, 0x0f, 0x19, 0x3c, 0x81, 0x95, 0xff, 0x68, 0xdf, 0x83, 0x76, 0x1b, 0x5c, 0xc8, 0x6d, 0xd6,
	0x16, 0x8d, 0xe8, 0x3f, 0x3d, 0x10, 0xe7, 0x7c, 0x9f, 0xc4, 0xdc, 0x21, 0xba, 0x67, 0xd0, 0x72,
	0x4c, 0x8e, 0x5d, 0x48, 0x19, 0xa6, 0x04, 0x4f, 0x19, 0xff, 0xbf, 0x1b, 0x3a, 0x40, 0x19, 0xad,
	0xe8, 0x32, 0x12, 0x72, 0xec, 0xc2, 0x36, 0xc3, 0xba, 0xbc, 0xf2, 0x99, 0xf1, 0x41, 0xf2, 0x74,
	0xd0, 0x66, 0x74, 0x60, 0x7e, 0xf5, 0x56, 0x2b, 0xb6, 0xad, 0x15, 0xfb, 0xac, 0x15, 0x7b, 0x6d,
	0x54, 0xb4, 0x6d, 0x54, 0xf4, 0xd1, 0xa8, 0xe8, 0xee, 0xa4, 0x3f, 0xd4, 0xcb, 0xac, 0x9f, 0xc3,
	0x66, 0x0d, 0x7e, 0x35, 0xa2, 0x53, 0x5d, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x75, 0x4f, 0x70,
	0xc5, 0xce, 0x01, 0x00, 0x00,
}

func (m *UserCredibility) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserCredibility) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserCredibility) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LoansList) > 0 {
		dAtA2 := make([]byte, len(m.LoansList)*10)
		var j1 int
		for _, num := range m.LoansList {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintUserCredibility(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x52
	}
	if m.TimesBorrowed != 0 {
		i = encodeVarintUserCredibility(dAtA, i, uint64(m.TimesBorrowed))
		i--
		dAtA[i] = 0x48
	}
	if m.TimesLent != 0 {
		i = encodeVarintUserCredibility(dAtA, i, uint64(m.TimesLent))
		i--
		dAtA[i] = 0x40
	}
	if len(m.TotalBorrowed) > 0 {
		i -= len(m.TotalBorrowed)
		copy(dAtA[i:], m.TotalBorrowed)
		i = encodeVarintUserCredibility(dAtA, i, uint64(len(m.TotalBorrowed)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.TotalLent) > 0 {
		i -= len(m.TotalLent)
		copy(dAtA[i:], m.TotalLent)
		i = encodeVarintUserCredibility(dAtA, i, uint64(len(m.TotalLent)))
		i--
		dAtA[i] = 0x32
	}
	if m.RiskLevel != 0 {
		i = encodeVarintUserCredibility(dAtA, i, uint64(m.RiskLevel))
		i--
		dAtA[i] = 0x28
	}
	if m.CreditScore != 0 {
		i = encodeVarintUserCredibility(dAtA, i, uint64(m.CreditScore))
		i--
		dAtA[i] = 0x20
	}
	if m.MinCollateralPercent != 0 {
		i = encodeVarintUserCredibility(dAtA, i, uint64(m.MinCollateralPercent))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintUserCredibility(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintUserCredibility(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintUserCredibility(dAtA []byte, offset int, v uint64) int {
	offset -= sovUserCredibility(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UserCredibility) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovUserCredibility(uint64(m.Id))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovUserCredibility(uint64(l))
	}
	if m.MinCollateralPercent != 0 {
		n += 1 + sovUserCredibility(uint64(m.MinCollateralPercent))
	}
	if m.CreditScore != 0 {
		n += 1 + sovUserCredibility(uint64(m.CreditScore))
	}
	if m.RiskLevel != 0 {
		n += 1 + sovUserCredibility(uint64(m.RiskLevel))
	}
	l = len(m.TotalLent)
	if l > 0 {
		n += 1 + l + sovUserCredibility(uint64(l))
	}
	l = len(m.TotalBorrowed)
	if l > 0 {
		n += 1 + l + sovUserCredibility(uint64(l))
	}
	if m.TimesLent != 0 {
		n += 1 + sovUserCredibility(uint64(m.TimesLent))
	}
	if m.TimesBorrowed != 0 {
		n += 1 + sovUserCredibility(uint64(m.TimesBorrowed))
	}
	if len(m.LoansList) > 0 {
		l = 0
		for _, e := range m.LoansList {
			l += sovUserCredibility(uint64(e))
		}
		n += 1 + sovUserCredibility(uint64(l)) + l
	}
	return n
}

func sovUserCredibility(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozUserCredibility(x uint64) (n int) {
	return sovUserCredibility(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UserCredibility) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUserCredibility
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserCredibility: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserCredibility: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserCredibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserCredibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUserCredibility
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUserCredibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCollateralPercent", wireType)
			}
			m.MinCollateralPercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserCredibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinCollateralPercent |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreditScore", wireType)
			}
			m.CreditScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserCredibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreditScore |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RiskLevel", wireType)
			}
			m.RiskLevel = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserCredibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RiskLevel |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalLent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserCredibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUserCredibility
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUserCredibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalLent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBorrowed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserCredibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUserCredibility
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUserCredibility
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalBorrowed = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimesLent", wireType)
			}
			m.TimesLent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserCredibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimesLent |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimesBorrowed", wireType)
			}
			m.TimesBorrowed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserCredibility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimesBorrowed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowUserCredibility
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.LoansList = append(m.LoansList, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowUserCredibility
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthUserCredibility
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthUserCredibility
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.LoansList) == 0 {
					m.LoansList = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowUserCredibility
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.LoansList = append(m.LoansList, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field LoansList", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipUserCredibility(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUserCredibility
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUserCredibility(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUserCredibility
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUserCredibility
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUserCredibility
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthUserCredibility
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupUserCredibility
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthUserCredibility
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthUserCredibility        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUserCredibility          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupUserCredibility = fmt.Errorf("proto: unexpected end of group")
)
